<template>
    <v-app toolbar footer dark>
        <page-header />
        <img src="./assets/octopus.png">
      <v-container>
        <main>
          <router-view></router-view>
        </main>
      </v-container>
    </v-app>
</template>

<script>
import PageHeader from '@/components/Header.vue'
export default {
  name: 'app',
  components: {
    PageHeader
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #8BBDB8;
  padding-top: 50px;
}
#app > img {
  width: 125px;
  height: 125px;
}
 nav a {
  color: #8BBDB8;
  text-decoration: none;
 }
 nav a:hover {
  text-decoration: underline;
 }

 /* Palette generated by Material Mixer - http://materialmixer.co/ */ 
 #app .container .dark-primary-color    { background: #000000; } 
 #app .container .dark-primary-color-text    { color: #000000; } 
 #app .container .default-primary-color { background: #212121; } 
 #app .container .light-primary-color   { background: #9E9E9E; } 
 #app .container .light-primary-color-text   { color: #9E9E9E; } 
 #app .container .accent-color          { background: #212121; } 
 #app .container .accent-light          { background: #FF9100; } 
 #app .container .accent-tint           { background: #FF8A33; } 
 #app .container .accent-shade          { background: #FA6700; } 
 #app .container .accent-shade-color          { color: #FA6700; } 
 #app .container .accent-button       { background: #212121; box-shadow: 0px 1px 0px #FF8A33 inset, 0px -1px 0px #FA6700 inset, 0px 0px 5px rgba(0, 0, 0, 0.5); }

</style>
