<template>
  <v-layout column>
    <v-flex xs12 md8 offset-md2>
      <Panel title="Songs">
          <v-btn 
            class="accent-shade"
            slot='action'
            light
            medium
            absolute
            right
            middle
            fab 
            @click="navigateTo({name: 'songs-create'})">
            <v-icon>add</v-icon>
          </v-btn>
        <div v-for="song in songs" :key="song.id">
          <Card 
            :title="song.title"
            :artist="song.artist"
            :album="song.album"
            :genre="song.genre"
            :id="song.id"
            :albumImageUrl="song.albumImageUrl"
            ></Card>
        </div>
      </Panel>
    </v-flex>
  </v-layout>
</template>
<script>
import SongService from '@/services/SongService'
import Panel from '@/components/Panel'
import Card from '@/components/Card'
export default {
  data () {
    return {
      songs: null
    }
  },
  methods: {
    navigateTo (route) {
      this.$router.push(route)
    }
  },
  components: {
    Panel,
    Card
  },
  async mounted () {
    var serverResponse = await SongService.getAllSongs()
    this.songs = serverResponse.data
  }
}
</script>
<style scoped>
  /* Palette generated by Material Mixer - http://materialmixer.co/ */ 
  .dark-primary-color    { background: #000000; } 
  .default-primary-color { background: #212121; } 
  .light-primary-color   { background: #9E9E9E; } 
  .accent-color          { background: #212121; } 
  .accent-light          { background: #FF9100; } 
  .accent-tint           { background: #FF8A33; } 
  .elevation-2 .toolbar .btn.accent-shade          { background-color: #FA6700; } 
  .accent-button       { background: #212121; box-shadow: 0px 1px 0px #FF8A33 inset, 0px -1px 0px #FA6700 inset, 0px 0px 5px rgba(0, 0, 0, 0.5); }
</style>